import { useState } from 'react';
import { Search, SlidersHorizontal, ChevronDown, X } from 'lucide-react';
import { FILTERS, SORTS, type FilterKey, type SortKey } from '@/useRequestState';

interface Props { filter: FilterKey; setFilter: (f: FilterKey) => void; search: string; setSearch: (s: string) => void; sort: SortKey; setSort: (s: SortKey) => void; counts: { found: number; withContacts: number; producers: number; withoutContacts: number; selected: number; sent: number; waiting: number; answered: number; }; }
const FILTER_COUNTS: Record<FilterKey, keyof Props['counts']> = { all: 'found', with_contacts: 'withContacts', producers: 'producers', without_contacts: 'withoutContacts', selected: 'selected', sent: 'sent', waiting: 'waiting', answered: 'answered' };
export function ListToolbar({ filter, setFilter, search, setSearch, sort, setSort, counts }: Props) {
  const [sortOpen, setSortOpen] = useState(false); const currentSort = SORTS.find((s) => s.key === sort)!;
  return <div className="sticky top-14 z-10 flex flex-col gap-3 border-b border-ink-200/70 bg-white px-6 lg:px-10 py-3 lg:top-0"><div className="flex items-center justify-between gap-4"><div className="flex items-baseline gap-2"><h2 className="text-sm font-semibold text-ink-800">Поставщики</h2><span className="text-xs text-ink-400">· {counts.found}</span></div><div className="flex items-center gap-2"><div className="relative"><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-ink-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Поиск поставщика, ИНН, сайта…" className="h-8 w-64 rounded-lg border border-ink-200 bg-ink-50/60 pl-8 pr-7 text-xs text-ink-700 placeholder:text-ink-400 transition-all focus:border-accent-400 focus:bg-white focus:outline-none focus:ring-2 focus:ring-accent-100" />{search && <button onClick={() => setSearch('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-ink-400 hover:text-ink-600"><X className="h-3.5 w-3.5" /></button>}</div><div className="relative"><button onClick={() => setSortOpen((v) => !v)} onBlur={() => setTimeout(() => setSortOpen(false), 120)} className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-ink-200 bg-white px-2.5 text-xs font-medium text-ink-600 transition-all hover:border-ink-300 hover:text-ink-800"><SlidersHorizontal className="h-3.5 w-3.5 text-ink-400" />{currentSort.label}<ChevronDown className="h-3 w-3 text-ink-400" /></button>{sortOpen && <div className="absolute right-0 top-9 z-20 w-44 animate-scale-in rounded-lg border border-ink-200 bg-white py-1 shadow-panel">{SORTS.map((s) => <button key={s.key} onMouseDown={() => { setSort(s.key); setSortOpen(false); }} className={`block w-full px-3 py-1.5 text-left text-xs transition-colors hover:bg-ink-50 ${s.key === sort ? 'font-medium text-accent-600' : 'text-ink-600'}`}>{s.label}</button>)}</div>}</div></div></div><div className="flex flex-wrap items-center gap-1.5">{FILTERS.map((f) => { const active = f.key === filter; const count = counts[FILTER_COUNTS[f.key]]; return <button key={f.key} onClick={() => setFilter(f.key)} className={['inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium transition-all', active ? 'bg-ink-800 text-white shadow-sm' : 'bg-ink-100/70 text-ink-600 hover:bg-ink-200/70 hover:text-ink-800'].join(' ')}>{f.label}<span className={['rounded-full px-1.5 py-px text-2xs font-semibold tabular-nums', active ? 'bg-white/20 text-white' : 'bg-white text-ink-500'].join(' ')}>{count}</span></button>; })}</div></div>;
}
